### ISSUE TITLE
Problem Loading Expert Demos

### ISSUE THREAD

**Issue by impulsecorp** [AurelianTactics/dqfd-with-keras#1]
I am unable to load the expert demos into keras_dqfd.py:

ubuntu@ip-172-31-43-76:~/dqfd-with-keras$ py keras_dqfd.py --game=SonicTheHedgehog-Genesis --demodir=retro-movies/human/SonicTheHedgehog-Genesis/contest
Using TensorFlow backend.
Training DQfD model
Traceback (most recent call last):
  File "keras_dqfd.py", line 700, in <module>
    expert_buffer.load_samples(args.ebuff_load_name)
  File "/home/ubuntu/dqfd-with-keras/per_replay.py", line 199, in load_samples
    temp_trans = pickle.load(open("{}.p".format(file_name), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'expert_transitions.p'

**Comment by SilverDash** [comment]
That's only if you've already trained an agent. You need to train an agent first.

python kreas_dqfd.py --train_expert 1 --demonumber [number of demos]

But you'll probably run into an error that I've yet to figure out.

```Using TensorFlow backend.
Training expert model
Traceback (most recent call last):
  File "py keras_dqfd.py", line 679, in <module>
    train_steps=750000)  #10 #750000
  File "py keras_dqfd.py", line 612, in train_expert_model
    exp_minibatch = exp_buffer.sample(batch_size)
  File "G:\Emulators\ML AI open AI\per_replay.py", line 151, in sample
    indices, probs = self.errors.sample(num_samples)
  File "G:\Emulators\ML AI open AI\per_replay.py", line 238, in sample
    assert self._used >= num_values
AssertionError
